apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-store
  template:
    metadata:
      labels:
        app: book-store
    spec:
      containers:
      - name: book-store
        image: katerinagligorovska/bookstoreapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: pod-port
        env:
        - name: DSN
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: dbConnStr
        
---
apiVersion: v1
kind: Service
metadata:
  name: book-store-service
spec:
  type: LoadBalancer
  selector:
    app: book-store
  ports:
  - protocol: TCP
    port: 8080
    targetPort: pod-port