apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |
    [auth.anonymous]
    enabled = true

    [users]
    allow_sign_up = true

    [security]
    admin_user=admin
    
    [session]
    cookie_secure = true
    cookie_samesite = strict
