apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-ingress
  annotations:
     kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /bookstore
        pathType: Prefix
        backend: 
          service:
            name: book-store-service
            port: 
              number: 8080
      - path: /prometheus
        pathType: Prefix
        backend:
          service:
            name: prometheus
            port: 
              number: 9090
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 3000