apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  dbConnStr: U2VydmVyPW1lbC5kYi5lbGVwaGFudHNxbC5jb207UG9ydD01NDMyO1VzZXJuYW1lPWNnY3Jldnp5O1Bhc3N3b3JkPW9TTVdVVngwOXRpVVdqeUZaTkRxdmJ4VlU3ZDdMNEFMO0RhdGFiYXNlPWNnY3Jldnp5Ow==




