scrape_configs:
- job_name: 'book-store'
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_label_app]
    action: keep
    regex: book-store
  metrics_path: /metrics