apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: LoadBalancer
  ports:
  - port: 9090
    targetPort: {{ .Values.containerPort }}
    protocol: TCP
  selector:
    app: {{ .Release.Name }}
