apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  annotations:
    prometheus.io/scrape: 'true'
spec:
  type: LoadBalancer
  selector:
    app: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: 8080
    targetPort: {{ .Values.podPortName }}
  
