name: Docker Build and Push to DockerHub

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver: docker

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: Build test stage
      uses: docker/build-push-action@v3
      with:
        push: false
        target: build
        tags: katerinagligorovska/bookstoreapp:${{github.sha}}

    - uses: addnab/docker-run-action@v3
      with:
        image: katerinagligorovska/bookstoreapp:${{github.sha}}
        run: dotnet test --no-restore --verbosity normal

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: katerinagligorovska/bookstoreapp:latest
